DROP SEQUENCE user_log_id_seq CASCADE;
DROP SEQUENCE user_id_seq CASCADE;
CREATE SEQUENCE user_log_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE SEQUENCE user_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
CREATE TABLE user_log (
  id INT NOT NULL,
  user_id INT DEFAULT NULL,
  url_from VARCHAR(255) NOT NULL,
  url_to VARCHAR(255) NOT NULL,
  log_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
  PRIMARY KEY(id)
);
CREATE INDEX IDX_6429094EA76ED395 ON user_log (user_id);
CREATE TABLE "user" (
  id INT NOT NULL,
  ip VARCHAR(32) UNIQUE NOT NULL,
  browser VARCHAR(255) NOT NULL,
  system VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
);
ALTER TABLE user_log ADD CONSTRAINT FK_6429094EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE;
